### ISSUE TITLE
Add an example for `Annotate` on nested values

### ISSUE THREAD

**Issue by danischm** [pulumi/pulumi-go-provider#109]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

I am having trouble annotating a nested data structure:

```
type Inputs struct {
	Children *[]Child `pulumi:"children,optional"`
}

type Child struct {
	Name string `pulumi:"name"`
}

func (c *Inputs) Annotate(a infer.Annotator) {
	a.Describe(???, "Name description")
}
```

What would be the right syntax or is this something not yet supported?

**Comment by iwahbe** [comment]
You should be able to just annotate `Child` struct directly.

```go
type Inputs struct {
	Children *[]Child `pulumi:"children,optional"`
}

type Child struct {
	Name string `pulumi:"name"`
}

func (c *Inputs) Annotate(a infer.Annotator) {
	a.Describe(&c.Children, "<your description here>")
}

func (c *Child) Annotate(a infer.Annotator) {
	a.Describe(&c, "<This is a child>")
	a.Describe(&c.Name, "Name description")
}
```

**Comment by danischm** [comment]
Indeed. Apologies, I must have been confused. Thx for you help!

**Comment by rajkumarGosavi** [comment]
@iwahbe I would like to go ahead and add an example in the documentation for nested annotation.

**Comment by iwahbe** [comment]
@rajkumarGosavi Great. I look forward to your PR.

**Comment by rajkumarGosavi** [comment]
@iwahbe any example or sample I can refer to to get an idea on how I can implement this?

**Comment by iwahbe** [comment]
This example has nested fields:

https://github.com/pulumi/pulumi-go-provider/blob/d3bbaee72bffee8589e8a9a0c89f83ca2ea2586b/examples/dna-store/main.go#L51-L61

https://github.com/pulumi/pulumi-go-provider/issues/109#issuecomment-1697731486 explains how to actually apply nested annotations.

Is that what you are looking for?

**Comment by rajkumarGosavi** [comment]
Hi @iwahbe I have raised a PR, please review it.
Thank you !!

**Comment by rajkumarGosavi** [comment]
@iwahbe
Thank you for allowing me to be a part of this great project.
Can you add `hacktoberfest-accepted` label to this PR, as I am participating in the event?

**Comment by iwahbe** [comment]
Pulumi has decided not to participate in hactoberfest.
