### ISSUE TITLE
Adding a default value for a non-string config attribute fails

### ISSUE THREAD

**Issue by danischm** [pulumi/pulumi-go-provider#111]
### What happened?

I would like to add a default value for a non-string config attribute using `Annotate()`:

```
type Config struct {
	Insecure          bool    `pulumi:"insecure"`
}

func (c *Config) Annotate(a infer.Annotator) {
	a.SetDefault(&c.Insecure, true, "ACI_INSECURE")
}
```

When using the provider (eg. `pulumi up`) I get the following error message:

```
    error: internal error: invalid property type: "boolean"
```

Removing the `a.SetDefault()` statement fixes the issue.

The full code is available here: https://github.com/netascode/pulumi-aci/blob/main/provider/pkg/provider/apic/config.go

### Expected Behavior

No error message.

### Steps to reproduce

Provided in description above.

### Output of `pulumi about`

CLI
Version 3.78.1
Go Version go1.20.7
Go Compiler gc

Host
OS darwin
Version 13.4.1
Arch arm64

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment]
Hey @danischm. Thanks for reporting this issue. We'll take a look and get this fixed.
