### ISSUE TITLE
Apply defaults to CheckConfigure

### ISSUE THREAD

**Issue by iwahbe** [pulumi/pulumi-go-provider#116]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Following up on https://github.com/pulumi/pulumi-go-provider/pull/114, we should apply the same defaults strategy to CheckConfigure.

**Comment by t0yv0** [comment]
I'm curious if this will run afoul of legacy transport forms for nested and secret values when passed to Config that the bridge had to work around with config_encoding: https://github.com/pulumi/pulumi-terraform-bridge/blob/fae3aa18d6346bfbb4ac21138dc8af11735829a7/pkg/tfbridge/config_encoding.go#L34

And is there any opportunity to lift out some shared code to libs?

**Comment by iwahbe** [comment]
I don't think that applying defaults will (since the provider **should**) isolate users from the old protocol. It looks like we don't though (causing https://github.com/pulumi/pulumi-go-provider/issues/111), so we will need to do that.

We should never use the old level, so I'm going to hide it from library users.
