### ISSUE TITLE
update pulumi sdk pkg

### ISSUE THREAD

**Issue by rawdaGastan** [pulumi/pulumi-go-provider#140]
### What happened?

It is not working with tha latest version of pulumi

### Example

not enough arguments in call to plugin.NewDetailedDiffFromObjectDiff
        have (*resource.ObjectDiff)
        want (*resource.ObjectDiff, bool)) (typecheck)
        "github.com/pulumi/pulumi-go-provider/infer"

### Output of `pulumi about`

CLI          
Version      3.90.1
Go Version   go1.21.3
Go Compiler  gc

Host     
OS       ubuntu
Version  22.04
Arch     x86_64

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment]
Thanks for pointing this out. A fix will come out shortly.
