### ISSUE TITLE
Export a Provider (maybe?)

### ISSUE THREAD

**Issue by MMartyn** [pulumi/pulumi-go-provider#189]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Currently our consumers are using YAML to consume our provider and there doesn't seem to be a good way to specify the version to use. I saw the discussion [here](https://github.com/pulumi/pulumi-yaml/issues/12) and the resulting example [here](https://github.com/pulumi/pulumi-yaml/pull/423/files#diff-e0a4229c45ce9229d5f7a923772a1b2550c26bcf202abc0afd7b1700a48d86d0). However, it isn't clear to me how to get this same versioning using this as there doesn't appear to be a provider type created for the provider. I would imagine I would need at the minimum the ability to set the version as well as a download url.

**Comment by mjeffryes** [comment]
@MMartyn it should be possible to specify the version for any provider in YAML. Can you offer more details on the provider and how it's used by your customers? 

Is the provider in the [Pulumi Registry](https://www.pulumi.com/registry/)?
Are users referring to the provider using a local path? (like the examples in this repo do eg [pulumi-go-provider/examples/file/consumer/Pulumi.yaml](https://github.com/pulumi/pulumi-go-provider/blob/main/examples/file/consumer/Pulumi.yaml)) 

Are they specifying the `pluginDownloadURL` (as described in [Pulumi YAML Reference](https://www.pulumi.com/docs/languages-sdks/yaml/yaml-language-reference/))? 

Regardless of source, there should be a valid `type` string you can use to specify the version as described in [Pulumi YAML Reference](https://www.pulumi.com/docs/languages-sdks/yaml/yaml-language-reference/#explicit-provider). The string should just be `pulumi:providers:` + the name of your provider. (eg. in the case of the "file" provider example linked to above the type string would be `pulumi:providers:file`

**Comment by MMartyn** [comment]
Ah ha that was the critical part that wasn't clear. I was doing `{name}:provider:Provider` but now I see it should be `pulumi:provider:{name}`. 

I was able to get it working with that. Thanks for the help.
