### ISSUE TITLE
Include option to fallback to specified environment variables when parsing config

### ISSUE THREAD

**Issue by danielrbradley** [pulumi/pulumi-go-provider#190]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Many providers and users leverage environment variables for providing ephemeral configuration instead of specifying configuration via Pulumi. We therefore need an option to specify which environment variables (in preference order) should be used to populate the configuration fields if not available in the PropertyMap.

This could perhaps look something like:

```go
type Config struct {
	Token string `pulumi:"token,optional,env:MYCLOUD_TOKEN,env:MYCLOUD_FALLBACK_TOKEN"`
}
```

**Comment by blampe** [comment]
@danielrbradley this should already be possible like so:
```
func (c *Config) Annotate(a infer.Annotator) {
	a.SetDefault(&c.Host, "", "DOCKER_HOST")
```

**Comment by danielrbradley** [comment]
Ah ok, that makes sense. That's a useful example to add to the docs if not already there.

Happy to close this out.
