### ISSUE TITLE
UpgradeResourceState

### ISSUE THREAD

**Issue by blampe** [pulumi/pulumi-go-provider#193]
Currently, if a resource is serialized with an older version of the schema there's no way to recover it short of manually edit the state file.

**Comment by iwahbe** [comment]
There are two major design considerations for implementing UpgradeResourceState:

- Is `UpgradeResourceState` handled entirely within `infer`, or does the main `pulumi-go-provider` package have a concept of an upgrade handling? My intuition is to start within `infer`, and only make state upgrades a first class feature of `pulumi-go-provider` when the RPC layer supports them. We could also make state upgrades a middleware consumed by `infer`, but I'm hesitant to design that with only one consumer.
- Should a state upgrade force a DIFF_SOME to ensure the new values get baked into the state. If we can do this cleanly, then my intuition is yes.


To be consistent with the current API, we would introduce a new interface in `infer`:

```go
type CustomStateUpgrade[O any] interface {
    func StateUpgrade(
        ctx p.Context, id string, oldState resource.PropertyMap,
    ) (didUpgrade bool, state O, err error)
}
```

Then any `CustomResource[I, O]` that implements `CustomStateUpgrade[O]` would opt into state upgrades. A typical implementation would probably look like this:

```go
// Upgrade from v0 state to v1 state.
func (*Resource) StateUpgrade(ctx p.Context, id string, state resource.PropertyMap) (bool, State, error) {
    if _, ok := isV0State(state); !ok {
        return false, State{}, nil
    }
    s, _, err := infer.DefaultCheck[StateV0](state)
    if err != nil {
        return false, State{}, err
    }
    return true, upgradeV0ToV1(s), nil
}
```

Under this model, users would be responsible for versioning their schema manually and inserting sentinel flags.
