### ISSUE TITLE
Unrecognized field 'pluginDownloadURL' on 'provider.Config'

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-go-provider#198]
### What happened?

A user is reporting an issue over the runpod/pulumi-runpod-native provider built with pulumi-go-provider, something is failing with 'Unrecognized field pluginDownloadURL'.

### Example

```
(runpod) ➜ pulumi up
Enter your passphrase to unlock config/secrets
    (set PULUMI_CONFIG_PASSPHRASE or PULUMI_CONFIG_PASSPHRASE_FILE to remember):  
Enter your passphrase to unlock config/secrets
Previewing update (tmpp):

Downloading plugin: 14.31 MiB / 14.31 MiB [=========================] 100.00% 0s

[resource plugin runpod-0.0.654] installing

     Type                        Name                                                                Plan       Info
 +   pulumi:pulumi:Stack         provider-runpod-native-tmpp                                         create     
     └─ pulumi:providers:runpod  default_0_0_654_github_/api.github.com/runpod/pulumi-runpod-native             2 errors

Diagnostics:
  pulumi:providers:runpod (default_0_0_654_github_/api.github.com/runpod/pulumi-runpod-native):
    error: pulumi:providers:runpod resource 'default_0_0_654_github_/api.github.com/runpod/pulumi-runpod-native': property version value {0.0.654} has a problem: Unrecognized field 'version' on 'provider.Config'
    error: pulumi:providers:runpod resource 'default_0_0_654_github_/api.github.com/runpod/pulumi-runpod-native': property pluginDownloadURL value {github://api.github.com/runpod/pulumi-runpod-native} has a problem: Unrecognized field 'pluginDownloadURL' on 'provider.Config'
```

### Output of `pulumi about`

N/A

### Additional context

In the bridged provider we have some special treatment for ignoring pluginDownloadURL and version fields passed two CheckConfig, see the "tolerate pluginDownloadURL":

https://github.com/pulumi/pulumi-terraform-bridge/blob/master/pf/tests/provider_checkconfig_test.go#L448

These fields may be sent by Pulumi CLI even though they are not part of the provider schema, so they're exceptional in some way. 

I could not find a pluginDownloadURL reference in this repo so perhaps something is not being handled quite right; cannot exclude the possibility that this is handled in pulumi/pulumi and linked here but the provider maintainers reporting the issue are using an outdated version.

CC @usrbinkat

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by pierre818181** [comment]
Output of pulumi about:

CLI          
Version      3.109.0
Go Version   go1.22.0
Go Compiler  gc

Plugins
NAME    VERSION
nodejs  unknown
runpod  0.0.655

Host     
OS       darwin
Version  13.4
Arch     arm64

This project is written in nodejs: executable='/Users/pierre_at_runpod/.nvm/versions/node/v18.19.0/bin/node' version='v18.19.0'

Backend        
Name           Prabuddhas-Laptop.local
URL            file://~
User           pierre_at_runpod
Organizations  
Token type     personal

Dependencies:
NAME                 VERSION
@pierre78181/runpod  0.0.655
@pulumi/pulumi       3.110.0
typescript           4.9.5
@types/node          14.18.63

Pulumi locates its logs in /var/folders/85/25qrq5xd04z8l7gvh_90t6740000gq/T/ by default
warning: Failed to get information about the current stack: No current snapshot

**Comment by pierre818181** [comment]
What ended up fixing the issue is one of:
- bumping up to the latest version of the pulumi/pulumi-go-provider
- adding a version trimmer in the main.go. 
```go
trimmedVersion := strings.TrimPrefix(runpod.Version, "v")
```

Hope pulumi incorporates the version trimmer by default because seems like a general use case.

**Comment by t0yv0** [comment]
Ah thanks for following up @pierre818181 , possibly this is fixed in the latest then.

**Comment by t0yv0** [comment]
Yea we should definitely revisit the version trimmer.
