### ISSUE TITLE
Design: Reconsider the semantics of `cancel.Wrap`

### ISSUE THREAD

**Issue by iwahbe** [pulumi/pulumi-go-provider#208]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Following up on the discussion from https://github.com/pulumi/pulumi-go-provider/pull/207, it seems like the as-designed behavior of the `cancel` middleware is unintuitive/unappealing to some.

The current behavior as described by `cancel`'s doc comment (PR pending) is:

```
// The `cancel` package provides a middle-ware that ties the Cancel gRPC call from Pulumi
// to Go's `context.Context` cancellation system.
//
// Wrapping a provider in `cancel.Wrap` ensures 2 things:
//
// 1. When a resource operation times out, the associated context is canceled.
//
// 2. When `Cancel` is called, all outstanding gRPC methods have their associated contexts
// canceled.
//
// A `cancel.Wrap`ed provider will still call the `Cancel` method on the underlying
// provider. If NotImplemented is returned, it will be swallowed.
```

This issue is a great place to comment on why the existing design should change.

**Comment by iwahbe** [comment]
For context, the bridge completely ignores the `Cancel` method:

[SDK](https://github.com/pulumi/pulumi-terraform-bridge/blob/d935ebadcba0d1d213d13757e3f5ab88b0d217ae/pkg/tfbridge/provider.go#L1496-L1499):
```go
// Cancel requests that the provider cancel all ongoing RPCs. For TF, this is a no-op.
func (p *Provider) Cancel(ctx context.Context, req *pbempty.Empty) (*pbempty.Empty, error) {
	return &pbempty.Empty{}, nil
}
```


[PF](https://github.com/pulumi/pulumi-terraform-bridge/blob/d935ebadcba0d1d213d13757e3f5ab88b0d217ae/pf/tfbridge/provider.go#L205-L213):

```go
// SignalCancellation asks all resource providers to gracefully shut down and abort any ongoing operations. Operation
// aborted in this way will return an error (e.g., `Update` and `Create` will either a creation error or an
// initialization error. SignalCancellation is advisory and non-blocking; it is up to the host to decide how long to
// wait after SignalCancellation is called before (e.g.) hard-closing any gRPC connection.
func (p *provider) SignalCancellationWithContext(_ context.Context) error {
	// Some improvements are possible here to gracefully shut down.
	return nil
}
```

**Comment by t0yv0** [comment]
The only point of implementing cancel would be to make some operation atomic with respect to cancellation to reduce the likelihood of exposing "partial states" exposed by interrupting such an operation in flight. Can we think of any? The stateful operation I'm thinking about is creating or updating a resource. It can be non-atomic if for example the provider creates a bucket first and then applies tags. Does this apply to the command provider, does it benefit from graceful cancel of a command? I'm apriori doubtful if any of the providers can meaningfully "gracefully cancel" these and would appreciate concrete evidence that it's helpful before throwing effort at implementing Cancel better at the generic level.

**Comment by t0yv0** [comment]
Right, right I'm with you that killing the provider is not always great answer, but if you're saying cancel cannot block, what are you saying will happen in the service provider in that scenario? Are you saying that Cancel handler will issue cancellation over context.Context object which will make Team.Create abort work but respond to the engine with "InitFailed" so that can be saved in state? I mean this:

```
// 2. When `Cancel` is called, all outstanding gRPC methods have their associated contexts
// canceled.
``` 

I haven't seen the code referenced that actually responds to the cancelled context, but skimming the docs just now it might be implicit in lower level networking code... So any kind of request handlers will stop waiting.

So this makes sense if we have some form of error recovery, like saving errors into state with &rpc.ErrorResourceInitFailed (which I still would love a quick page on what that does precisely). If you want to speed up this error recovery this makes total sense. If it was just injecting unrecoverable errors it didn't make sense to me as it seemed to be swapping one way to crash for another way to crash.

**Comment by iwahbe** [comment]
> Are you saying that Cancel handler will issue cancellation over context.Context object which will make Team.Create abort work but respond to the engine with "InitFailed" so that can be saved in state? 

Yes! That's exactly what I'm saying.

>I haven't seen the code referenced that actually responds to the cancelled context, but skimming the docs just now it might be implicit in lower level networking code... So any kind of request handlers will stop waiting.

Yes. Any high quality library with ongoing operations should cancel immediately. This includes go's standard library, for both network requests and subprocesses. Most providers (pulumi-command and pulumi-pulumiservice included) will get instant cancelation for free.

**Comment by iwahbe** [comment]
This hasn't come up again, and I think the design is pretty solid.

I definitely think that reducing the scope of the cancel wrapper would hurt the default experience. Until and unless the Pulumi provider protocol allows providers to block a cancel operation, we need to default to the safest `Cancel` behavior, which is graceful termination of all ongoing tasks.
