### ISSUE TITLE
Asset properties can be Archives at runtime

### ISSUE THREAD

**Issue by danielrbradley** [pulumi/pulumi-go-provider#237]
When defining a property of type `resource.Asset`, the generated schema will contain a `$ref` of `pulumi.json#/Asset`. However, in the SDKs, an "asset" is represented by `pulumi.AssetOrArchive` because an archive is currently always a valid asset.

Therefore, when deserializing the PropertyValue for the provider to use, it's valid for the user to have specified one of the Archive types which then isn't deserializable into the `resource.Asset` field within the provider.

1. We need instead a new `resource.AssetOrArchive` type to be used with the go-provider.
2. We need to handle reflecting over `resource.AssetOrArchive`
3. Using `resource.Asset` in a provider field should be considered an error. Though initially this should be a warning to avoid a breaking change but should be upgraded to an error on the next major release.

**Comment by thomas11** [comment]
Tagging P1 since will be blocking the v1release of the command provider.

**Comment by iwahbe** [comment]
We are on v0.17.0. We can make breaking changes now (and we should if this leads to an unexpected runtime error).

**Comment by iwahbe** [comment]
An ideal solution would be that we use `resource.AssetOrArchive` (maybe `infer.AssetOrArchive`) to communicate either an asset or archive. We can later re-enable the use of `resource.Asset` when we can specify in the schema that `resource.Asset` only supports assets, not archives.
