### ISSUE TITLE
Add ability to easily mark output of an invoke as secret

### ISSUE THREAD

**Issue by zbuchheit** [pulumi/pulumi-go-provider#259]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

I would like to be able to mark the output of an invoke as always secret similar to how it can be done today for a resource being created with `provider:"secret"`. I expect this is likely because the outputs of the functions are plain strings and not `pulumi.Output`

**Comment by t0yv0** [comment]
I believe this needs https://github.com/pulumi/pulumi/issues/12710 codegen work to complete.
