### ISSUE TITLE
framework generates bad include statements

### ISSUE THREAD

**Issue by Joerit** [pulumi/pulumi-go-provider#280]
### What happened?

Lets start off by saying: I'm not entirely sure i'm doing things correctly.

it seems to render out placeholder domain names in the imports
e.g.  `"example.com/pulumi-greetings/sdk/go/greetings/internal"`
instead of the correct ` "my.domain.name/pulumi-greetings/sdk/go/greetings/internal"`

### Example

`go mod init my.domain.com/pulumi-mymodule`

copy the hello-world example to main.go
update the name: `p.RunProvider("greeter", "0.1.0",` `p.RunProvider("mymodule", "0.1.0",`

add imports:
```
package main
import (
    "fmt"
    "context"
    "strings"

    p "github.com/pulumi/pulumi-go-provider"
    "github.com/pulumi/pulumi-go-provider/infer"
)
```

go get the modules:
`go get github.com/pulumi/pulumi-go-provider/infer`
`go get github.com/pulumi/pulumi-go-provider`

`go build`

let it render out sdk files:
`pulumi package gen-sdk --logtostderr ./pulumi-mymodule`

this renders out bad import statements:
``` head sdk/go/greetings/init.go
// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package greetings

import (
        "fmt"

        "example.com/pulumi-mymodule/sdk/go/mymodule/internal"
        "github.com/blang/semver"
...
``` 

### Output of `pulumi about`

pulumi about
CLI          
Version      3.131.0
Go Version   go1.23.0
Go Compiler  gc

Host     
OS       fedora
Version  40
Arch     x86_64

Backend        
Name           fedora
URL            file://~
User           ratty
Organizations  
Token type     personal

### Additional context

my go env:

GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/home/ratty/.cache/go-build'
GOENV='/home/ratty/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/home/ratty/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/home/ratty/go'
GOPRIVATE=''
GOPROXY='direct'
GOROOT='/usr/lib/golang'
GOSUMDB='off'
GOTMPDIR=''
GOTOOLCHAIN='local'
GOTOOLDIR='/usr/lib/golang/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.22.6'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/gits/dwse/ops/pulumi-providers/pulumi-mymodule/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build4086847819=/tmp/go-build -gno-record-gcc-switches'

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment]
Hi @Joerit. Unfortunately, Go requires the code to know where it lives. You need to set the Go import base path to where your SDK is hosted:

This is how [pulumi-command](https://github.com/pulumi/pulumi-command/blob/e5a0bbcf9872db04d202349cd512eda2ba2e0a4d/provider/pkg/provider/provider.go#L59) does it.

It would look like:

```patch
	return infer.Provider(infer.Options{
+		Metadata: schema.Metadata{
+			LanguageMap: map[string]any{
+				"go": map[string]any{
+					"importBasePath":                 "my.domain.name/pulumi-greetings/sdk/go/greetings",
+				}
+			}
+		}
```

**Comment by Joerit** [comment]
@iwahbe that's exactly what i was missing

thank you for linking to that pulumi-command repo, there's a lot of example there
