### ISSUE TITLE
method to make field Computed?

### ISSUE THREAD

**Issue by dixler** [pulumi/pulumi-go-provider#75]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

I was working on https://github.com/pulumi/pulumi-command/issues/166. Afaik there's not a way to indicate that a field is computed. I believe that the provider is returning an empty string.

Some ideas:
- [ ] make properties on resources computed by default
- [ ] extend WireDependencies

**Comment by iwahbe** [comment]
There isn't a way to mark a field as "always computed". 

Computed-ness should be part of the depends on relationship defined by [`infer.OutputField.DependsOn`](https://github.com/pulumi/pulumi-go-provider/blob/1eebd67cd8ea3c4bd58dd026a2cdef3621fb5fa5/infer/resource.go#L199). It looks like the problem occurs when we trigger an update without any input changing.

**Comment by jkodroff** [comment]
I'm seeing spurious quote marks around `command.local.Command.stdout` which is causing a similar issue with JSON parsing (in my case, from an AWS CLI command).
