### ISSUE TITLE
warning: Missing expect call to 'Check' before 'Diff' for resource "xyz"

### ISSUE THREAD

**Issue by dixler** [pulumi/pulumi-go-provider#77]
A user reported https://github.com/pulumi/pulumi-command/issues/173 because they were getting a warning in the command provider from this library.

How can we fix this warning?

Something to note is that `triggers` has the tag `replaceOnChanges`.

> ### What happened?
> When updating a stack I recently get a warning for all affected command resources ` warning: Missing expect call to 'Check' before 'Diff' for resource "urn:pulumi:<REMOVED>$command:remote:Command::<REMOVED>"`
> 
> ### Steps to reproduce
> Create a pulumi stack with command resources that have triggers configured.
> 
> ### Expected Behavior
> Either the warning is not shown or an actionable/user-friendly message is shown.
> 
> ### Actual Behavior
> Cryptic warnings are shown.
> 
> ### Output of `pulumi about`
> CLI Version 3.50.2 Go Version go1.19.4 Go Compiler gc
> 
> Plugins NAME VERSION command 0.7.0 command 0.7.0 command 0.7.0 command 0.7.0 kubernetes 3.23.1 nodejs unknown vsphere 4.3.0
> 
> Host OS Microsoft Windows 10 Pro Version 10.0.19045 Build 19045 Arch x86_64
> 
> This project is written in nodejs: executable='node.exe' version='v18.12.1'
> 
> ### Additional context
> The warning is generated here: https://github.com/pulumi/pulumi-go-provider/blob/996b11838d4b550a817c8015efa512564cb8c13b/infer/resource.go#L446
> 
> ### Contributing
> Vote on this issue by adding a +1 reaction. To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
This looks like go-provider is stateful? That's not ideal, I do not want to maintain a contract with providers that Check will always be called before other operations (It's clearly not true today given https://github.com/pulumi/pulumi-command/issues/173)

**Comment by iwahbe** [comment]
The provider is/was stateful to help debug it during development, but doesn't need to be. We can rip out that warning without any ill effects.

**Comment by runatyr1** [comment]
Hi @thomas11 @iwahbe 

I'm getting this warning now with the latest version of Pulumi. This happens even if I re-deploy a stack (meaning no changes can be happening). I'd be glad to assist debugging this or if it's safe to remove the warning please remove.
