### ISSUE TITLE
Generate docs with registrygen (export schema.json)

### ISSUE THREAD

**Issue by tmkontra-zeet** [pulumi/pulumi-go-provider#79]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

- We have implemented a pulumi provider using this framework: https://github.com/zeet-dev/pulumi-zeet
- We would now like to generate docs for the provider: https://github.com/pulumi/registrygen
  - `registrygen generate docs` requires a `schema.json` file
  - we have not authored a `schema.json` (my understanding is that the go provider generates one in-memory at runtime?)
  - Is there a way to have `registrygen` interface with our provider implementation, and generate docs?

### Affected area/feature

- schema.json
- registrygen

**Comment by iwahbe** [comment]
I'm not aware of a way for `regestrygen` to interface directly with a provider. You can extract the schema from any provider with `pulumi package get-schema`. You can point `get-schema` at a provider binary, and it will emit the `schema.json`. At that point, you can invoke `registrygen` normally.
