### ISSUE TITLE
Update documentation to indicate preview status

### ISSUE THREAD

**Issue by AaronFriel** [pulumi/pulumi-go-provider#80]
The README notes this is in active development and users should wait to use this, however we've now released a provider ([Command](https://github.com/pulumi/pulumi-command/)) using this SDK and expect to support it and encourage use.

This project should likely be considered in preview status, as pre-1.0, but with intent to GA. Provider implementations are needed and should be encouraged.

**Comment by lukehoban** [comment]
Not sure what concretely this is tracking - given that the README does note the status. I think this is okay to close - and to focus on plan for GA.
